print(">> Daftar Tiket <<")
print("Source Code by Nelshen Yong")
print("-"*20)
print("JURUSAN:")
print("1. Prabumulih")
print("2. Muara Enim")
print("3. Lubuk Linggau")
print("-"*20)

tiket = int(input("Pilih jurusan (1 / 2 / 3): "))

if tiket == 1:
    print("KELAS")
    print("-"*20)
    print("JURUSAN:")
    print("1. Ekonomi")
    print("2. Bisnis")
    print("3. Eksekutif")
    print("-"*20)
    kelas = int(input("Pilih kelas (1 / 2 / 3): "))
    if kelas == 1:
        print("Tiket Ekonomi - Prabumulih Rp100.000")
        p_eko = int(input("Jumlah tiket: "))
        print(f"Harga tiket\t: \tRp100.000")
        print(f"Harga subtotal\t: \tRp{100000 * p_eko}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{100000 * p_eko}")
    elif kelas == 2:
        print("Tiket Bisnis - Prabumulih Rp400.000")
        p_bis = int(input("Jumlah tiket: "))
        print(f"Harga tiket\t: \tRp400.000")
        print(f"Harga subtotal\t: \tRp{400000 * p_bis}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{400000 * p_bis}")
    elif kelas == 3:
        print("Tiket Bisnis - Prabumulih Rp700.000")
        p_eks = int(input("Jumlah tiket: "))
        print("-"*20)
        print(f"Harga tiket\t: \tRp700.000")
        print(f"Harga subtotal\t: \tRp{700000 * p_eks}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{700000 *  p_eks}")
    else :
        print("Pilihan Tidak Tersedia!")
        print("Source Code by Nelshen Yong")

elif tiket == 2:
    print("KELAS")
    print("-"*20)
    print("JURUSAN:")
    print("1. Ekonomi")
    print("2. Bisnis")
    print("3. Eksekutif")
    print("-"*20)
    kelas = int(input("Pilih kelas (1 / 2 / 3): "))
    if kelas == 1:
        print("Tiket Ekonomi - Muara Enim Rp200.000")
        m_eko = int(input("Jumlah tiket: "))
        promo = str(input("Kode promo: "))
        if promo.lower() == "igs":
            print("-"*20)
            print(f"Harga tiket\t: \tRp200.000")
            print(f"Harga subtotal\t: \tRp{200000 * m_eko}")
            print(f"Diskon\t\t: \tRp{200000 - (200000 * 0.10)}")
            print(f"Harga total\t: \tRp{(200000 * m_eko) - (200000 * 0.10)}")
        if promo == "":
            print("-"*20)
            print(f"Harga tiket\t: \tRp200.000")
            print(f"Harga subtotal\t: \tRp{200000 * m_eko}")
            print(f"Diskon\t\t: \tRp0")
            print(f"Harga total\t: \tRp{200000 * m_eko}")
    elif kelas == 2:
        print("Tiket Bisnis - Muara Enim Rp500.000")
        m_bis = int(input("Jumlah tiket: "))
        print("-"*20)
        print(f"Harga tiket\t: \tRp500.000")
        print(f"Harga subtotal\t: \tRp{500000 * m_bis}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{500000 * m_bis}")
    elif kelas == 3:
        print("Tiket Bisnis - Muara Enim Rp800.000")
        m_eks = int(input("Jumlah tiket: "))
        print("-"*20)
        print(f"Harga tiket\t: \tRp800.000")
        print(f"Harga subtotal\t: \tRp{800000 * m_eks}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{800000 * m_eks}")
    else :
        print("Pilihan Tidak Tersedia!")
        print("Source Code by Nelshen Yong")

elif tiket == 3:
    print("KELAS")
    print("-"*20)
    print("JURUSAN:")
    print("1. Ekonomi")
    print("2. Bisnis")
    print("3. Eksekutif")
    print("-"*20)
    kelas = int(input("Pilih kelas (1 / 2 / 3): "))
    if kelas == 1:
        print("Tiket Ekonomi - Lubuk Linggau Rp300.000")
        l_eko = int(input("Jumlah tiket: "))
        print("-"*20)
        print(f"Harga tiket\t: \tRp300.000")
        print(f"Harga subtotal\t: \tRp{300000 * l_eko}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{300000 * l_eko}")
    elif kelas == 2:
        print("Tiket Bisnis - Lubuk Linggau Rp600.000")
        l_bis = int(input("Jumlah tiket: "))
        print("-"*20)
        print(f"Harga tiket\t: \tRp600.000")
        print(f"Harga subtotal\t: \tRp{600000 * l_bis}")
        print(f"Diskon\t\t: \tRp0")
        print(f"Harga total\t: \tRp{600000 * l_bis}")
    elif kelas == 3:
        print("Tiket Bisnis - Lubuk Linggau Rp900.000")
        l_eks = int(input("Jumlah tiket: "))
        print(f"Harga tiket: {900000 * l_eks}")
        promo = str(input("Kode promo: "))
        if promo.lower() == "igs":
            print("-"*20)
            print(f"Harga tiket\t: \tRp900.000")
            print(f"Harga subtotal\t: \tRp{900000 * l_eks}")
            print(f"Diskon\t\t: \tRp{(900000) - (900000 * 0.10)}")
            print(f"Harga total\t: \tRp{(900000 * l_eks) - (200000 * 0.10)}")
        if promo == "":
            print("-"*20)
            print(f"Harga tiket\t: \tRp900.000")
            print(f"Harga subtotal\t: \tRp{900000 * l_eks}")
            print(f"Diskon\t\t: \tRp0")
            print(f"Harga total\t: \tRp{900000 * l_eks}")
    else :
        print("Pilihan Tidak Tersedia!")
        print("Source Code by Nelshen Yong")
else :
    print("Pilihan Tidak Tersedia!")
    print("Source Code by Nelshen Yong")